server:
  tomcat:
    uri-encoding:UTF-8
  port: 8088
  max-http-header-size: 80KB

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oss?useServerPrepStmts=false&serverTimezone=GMT%2B8
    username: root
    password: 1234
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 500000
      pool-name: DataSourceHikariCP
      max-lifetime: 1800000
      connection-test-query: SELECT  1

mybatis:
  type-aliases-package: com.xuming.pojo
  mapper-locations: classpath:mapper/*.xml

